services:

  #
  # The API gateway routes to the OAuth Agent and runs an OAuth proxy plugin
  # During API requests the OAuth proxy decrypts cookies and forwards JWT access tokens to APIs
  #
  apigateway:
    image: apigateway:latest
    hostname: apigateway-internal
    extra_hosts:
     - api.authsamples-dev.com:host-gateway
    ports:
      - 444:8000
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml
      - ../certs/authsamples-dev.ssl.crt:/usr/local/share/certs/authsamples-dev.ssl.crt
      - ../certs/authsamples-dev.ssl.key:/usr/local/share/certs/authsamples-dev.ssl.key
      - ../certs/authsamples-dev.ca.crt:/usr/local/share/certs/authsamples-dev.ca.crt
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: '/usr/local/kong/declarative/kong.yml'
      KONG_PROXY_LISTEN: '0.0.0.0:8000 http2 ssl'
      KONG_SSL_CERT: '/usr/local/share/certs/authsamples-dev.ssl.crt'
      KONG_SSL_CERT_KEY: './usr/local/share/certs/authsamples-dev.ssl.key'
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: './usr/local/share/certs/authsamples-dev.ca.crt'
      KONG_LOG_LEVEL: 'info'
      KONG_PLUGINS: 'bundled,oauth-proxy'
      KONG_NGINX_PROXY_PROXY_BUFFERS: '8 8k'
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: '8k'

  #
  # The OAuth Agent is a utility API that runs behind the API gateway
  #
  oauthagent:
    image: oauthagent:latest
    hostname: oauthagent-internal
    volumes:
      - ../certs/authsamples-dev.ca.crt:/usr/local/share/certs/authsamples-dev.ca.crt
    env_file:
      - ./oauthagent/oauthagent.env
