_format_version: '3.0'
_transform: true

services:

- name: oauth-agent
  url: http://oauthagent-internal:8000/oauth-agent
  routes:
  - name: oauth-agent-api-route
    hosts:
    - bfflocal.authsamples-dev.com
    paths:
    - /oauth-agent

- name: finalapi
  url: https://api.authsamples-dev.com:446/investments
  routes:
  - name: finalapi-route
    hosts:
    - bfflocal.authsamples-dev.com
    paths:
    - /investments
  plugins:
  - name: cors
    config:
      origins:
      - https://www.authsamples-dev.com
      credentials: true
      max_age: 86400
  - name: oauth-proxy
    config:
      encryption_key: 33be02f1b76feccf2c30a4847b0ad68d01756d7a9fb7f9a533b12b5d249a9c66
      cookie_name_prefix: authsamples

- name: oauthuserinfo
  url: https://login.authsamples.com/oauth2/userInfo
  routes:
  - name: oauthuserinfo-route
    hosts:
    - bfflocal.authsamples-dev.com
    paths:
    - /oauthuserinfo
  plugins:
  - name: cors
    config:
      origins:
      - https://www.authsamples-dev.com
      credentials: true
      max_age: 86400
  - name: oauth-proxy
    config:
      encryption_key: 33be02f1b76feccf2c30a4847b0ad68d01756d7a9fb7f9a533b12b5d249a9c66
      cookie_name_prefix: authsamples
